// Generates src/data/robots.ts from the 配置清单 table in docs/电控组/robot-configs.md.
//
//   node scripts/gen-robots.js           rewrite src/data/robots.ts
//   node scripts/gen-robots.js --check   exit 1 when src/data/robots.ts is out of date
//
// The table is the single source for which YAML files exist and what each one configures.
// This script adds only what the table does not say: which files belong to which robot on the
// home page, the module names behind each function, and the related documents.
// A function the table lists but FUNCTION_MODULES does not know stops the script, so a new
// entry in the table is never dropped silently.

const fs = require('fs');
const path = require('path');

const SITE = path.resolve(__dirname, '..');
const SOURCE = 'docs/电控组/robot-configs.md';
const TARGET = 'src/data/robots.ts';

// Robots shown on the home page, in display order. The first file of each robot provides the
// function list; further files contribute their own line from the table.
const ROSTER = [
  {
    id: 'hero',
    name: '英雄',
    glyph: '英',
    refereeId: '1',
    files: ['hero.yaml'],
    docs: [
      { href: '/电控组/robot-configs', label: '机器人配置' },
      { href: '/电控组/modules', label: '模块索引' },
    ],
  },
  {
    id: 'infantry',
    name: '步兵',
    glyph: '步',
    refereeId: '3–5',
    files: ['omni_infantry_3.yaml', 'omni_infantry_4.yaml'],
    docs: [
      { href: '/电控组/robot-configs', label: '机器人配置' },
      { href: '/电控组/communication-standard', label: '通信规范' },
      { href: '/算法组/camera-pipeline', label: '相机与同步' },
    ],
  },
  {
    id: 'sentry',
    name: '哨兵',
    glyph: '哨',
    refereeId: '7',
    files: ['sentry.yaml'],
    docs: [
      { href: '/电控组/robot-configs', label: '机器人配置' },
      { href: '/算法组/sync-and-config', label: '运行配置' },
    ],
  },
  {
    id: 'aerial',
    name: '空中',
    glyph: '空',
    refereeId: '6',
    files: ['aerial.yaml'],
    docs: [
      { href: '/电控组/robot-configs', label: '机器人配置' },
      { href: '/电控组/hardware-mapping', label: '外设映射' },
    ],
  },
  {
    id: 'dart',
    name: '飞镖',
    glyph: '镖',
    refereeId: '8',
    files: ['dart.yaml'],
    docs: [
      { href: '/电控组/robot-configs', label: '机器人配置' },
      { href: '/电控组/modules', label: '模块索引' },
    ],
  },
];

// Function names used in the table -> module repositories (docs/电控组/modules.md).
const FUNCTION_MODULES = {
  底盘: ['Chassis'],
  全向底盘: ['Chassis'],
  云台: ['Gimbal'],
  MiniGimbal: ['MiniGimbal'],
  HeroLauncher: ['HeroLauncher'],
  步兵发射机构: ['InfantryLauncher'],
  Dart: ['Dart'],
  功率管理: ['SuperPower', 'PowerControl'],
  通信: ['SharedTopic', 'SharedTopicClient'],
  主机通信: ['SharedTopic', 'SharedTopicClient'],
  相机同步: ['CameraSync'],
  SentryProtocol: ['SentryProtocol'],
  姿态: ['BMI088', 'MadgwickAHRS'],
  遥控: ['DR16'],
  电机: ['RMMotor'],
  裁判: ['Referee'],
};

function parseTable(markdown) {
  const start = markdown.indexOf('## 配置清单');
  if (start < 0) throw new Error(`${SOURCE}: heading "## 配置清单" not found`);
  const rest = markdown.slice(start + 1);
  const end = rest.indexOf('\n## ');
  const section = end < 0 ? rest : rest.slice(0, end);
  const rows = new Map();
  for (const line of section.split(/\r?\n/)) {
    const m = /^\|\s*`([^`]+\.yaml)`\s*\|\s*(.+?)\s*\|\s*$/.exec(line);
    if (m) rows.set(m[1], m[2]);
  }
  if (!rows.size) throw new Error(`${SOURCE}: no rows in the 配置清单 table`);
  return rows;
}

function build() {
  const markdown = fs.readFileSync(path.join(SITE, SOURCE), 'utf8');
  const rows = parseTable(markdown);
  const used = new Set();
  const robots = ROSTER.map((entry) => {
    const files = entry.files.map((file) => {
      if (!rows.has(file)) throw new Error(`${SOURCE}: ${file} is not in the 配置清单 table`);
      used.add(file);
      return { file, path: `User/RobotConfig/${file}`, summary: rows.get(file) };
    });
    const functions = files[0].summary.split('、').map((s) => s.trim()).filter(Boolean);
    const modules = [];
    for (const fn of functions) {
      const names = FUNCTION_MODULES[fn];
      if (!names) throw new Error(`${SOURCE}: unknown function "${fn}" in ${files[0].file}; add it to FUNCTION_MODULES`);
      for (const name of names) if (!modules.includes(name)) modules.push(name);
    }
    return {
      id: entry.id,
      name: entry.name,
      glyph: entry.glyph,
      refereeId: entry.refereeId,
      files,
      functions,
      modules,
      command: `xrobot_gen_main --config ${files[0].path}`,
      docs: entry.docs,
    };
  });
  const omitted = [...rows.entries()]
    .filter(([file]) => !used.has(file))
    .map(([file, summary]) => ({ file, summary }));

  return `// Generated by scripts/gen-robots.js from ${SOURCE}. Do not edit by hand:
// change the table (or the roster in the script) and run \`node scripts/gen-robots.js\`.

export type RobotConfigFile = {
  /** File name in User/RobotConfig/. */
  file: string;
  /** Path from the bsp-dev-c root. */
  path: string;
  /** The 已配置的主要功能 cell of the table. */
  summary: string;
};

export type Robot = {
  id: 'hero' | 'infantry' | 'sentry' | 'aerial' | 'dart';
  /** 兵种 name. */
  name: string;
  /** One character for the armour plate on the card. */
  glyph: string;
  /** Robot ID in the RoboMaster referee system (red side). */
  refereeId: string;
  files: RobotConfigFile[];
  /** Functions of the first file, split from the table. */
  functions: string[];
  /** Module repositories behind those functions (docs/电控组/modules.md). */
  modules: string[];
  /** Generates User/xrobot_main.hpp for the first file. */
  command: string;
  docs: { href: string; label: string }[];
};

export const ROBOT_SOURCE_DOC = '/电控组/robot-configs';

export const ROBOTS: Robot[] = ${JSON.stringify(robots, null, 2)};

/** Files in the table that the home page does not show (no complete robot yet). */
export const OMITTED_CONFIGS: { file: string; summary: string }[] = ${JSON.stringify(omitted, null, 2)};
`;
}

const output = build();
const target = path.join(SITE, TARGET);
if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (current !== output) {
    console.error(`${TARGET} is out of date; run node scripts/gen-robots.js`);
    process.exit(1);
  }
  console.log(`${TARGET} is up to date`);
} else {
  fs.writeFileSync(target, output, 'utf8');
  console.log(`wrote ${TARGET}`);
}
