// Generated by scripts/gen-robots.js from docs/电控组/robot-configs.md. Do not edit by hand:
// change the table (or the roster in the script) and run `node scripts/gen-robots.js`.

export type RobotConfigFile = {
  /** File name in User/RobotConfig/. */
  file: string;
  /** Path from the bsp-dev-c root. */
  path: string;
  /** The 已配置的主要功能 cell of the table. */
  summary: string;
};

export type Robot = {
  id: 'hero' | 'infantry' | 'sentry' | 'aerial' | 'dart';
  /** 兵种 name. */
  name: string;
  /** One character for the armour plate on the card. */
  glyph: string;
  /** Robot ID in the RoboMaster referee system (red side). */
  refereeId: string;
  files: RobotConfigFile[];
  /** Functions of the first file, split from the table. */
  functions: string[];
  /** Module repositories behind those functions (docs/电控组/modules.md). */
  modules: string[];
  /** Generates User/xrobot_main.hpp for the first file. */
  command: string;
  docs: { href: string; label: string }[];
};

export const ROBOT_SOURCE_DOC = '/电控组/robot-configs';

export const ROBOTS: Robot[] = [
  {
    "id": "hero",
    "name": "英雄",
    "glyph": "英",
    "refereeId": "1",
    "files": [
      {
        "file": "hero.yaml",
        "path": "User/RobotConfig/hero.yaml",
        "summary": "底盘、云台、MiniGimbal、HeroLauncher、功率管理、通信"
      }
    ],
    "functions": [
      "底盘",
      "云台",
      "MiniGimbal",
      "HeroLauncher",
      "功率管理",
      "通信"
    ],
    "modules": [
      "Chassis",
      "Gimbal",
      "MiniGimbal",
      "HeroLauncher",
      "SuperPower",
      "PowerControl",
      "SharedTopic",
      "SharedTopicClient"
    ],
    "command": "xrobot_gen_main --config User/RobotConfig/hero.yaml",
    "docs": [
      {
        "href": "/电控组/robot-configs",
        "label": "机器人配置"
      },
      {
        "href": "/电控组/modules",
        "label": "模块索引"
      }
    ]
  },
  {
    "id": "infantry",
    "name": "步兵",
    "glyph": "步",
    "refereeId": "3–5",
    "files": [
      {
        "file": "omni_infantry_3.yaml",
        "path": "User/RobotConfig/omni_infantry_3.yaml",
        "summary": "全向底盘、云台、步兵发射机构、相机同步、通信"
      },
      {
        "file": "omni_infantry_4.yaml",
        "path": "User/RobotConfig/omni_infantry_4.yaml",
        "summary": "另一份全向步兵配置，设备分配和参数单独维护"
      }
    ],
    "functions": [
      "全向底盘",
      "云台",
      "步兵发射机构",
      "相机同步",
      "通信"
    ],
    "modules": [
      "Chassis",
      "Gimbal",
      "InfantryLauncher",
      "CameraSync",
      "SharedTopic",
      "SharedTopicClient"
    ],
    "command": "xrobot_gen_main --config User/RobotConfig/omni_infantry_3.yaml",
    "docs": [
      {
        "href": "/电控组/robot-configs",
        "label": "机器人配置"
      },
      {
        "href": "/电控组/communication-standard",
        "label": "通信规范"
      },
      {
        "href": "/算法组/camera-pipeline",
        "label": "相机与同步"
      }
    ]
  },
  {
    "id": "sentry",
    "name": "哨兵",
    "glyph": "哨",
    "refereeId": "7",
    "files": [
      {
        "file": "sentry.yaml",
        "path": "User/RobotConfig/sentry.yaml",
        "summary": "底盘、云台、步兵发射机构、SentryProtocol、功率管理、通信"
      }
    ],
    "functions": [
      "底盘",
      "云台",
      "步兵发射机构",
      "SentryProtocol",
      "功率管理",
      "通信"
    ],
    "modules": [
      "Chassis",
      "Gimbal",
      "InfantryLauncher",
      "SentryProtocol",
      "SuperPower",
      "PowerControl",
      "SharedTopic",
      "SharedTopicClient"
    ],
    "command": "xrobot_gen_main --config User/RobotConfig/sentry.yaml",
    "docs": [
      {
        "href": "/电控组/robot-configs",
        "label": "机器人配置"
      },
      {
        "href": "/算法组/sync-and-config",
        "label": "运行配置"
      }
    ]
  },
  {
    "id": "aerial",
    "name": "空中",
    "glyph": "空",
    "refereeId": "6",
    "files": [
      {
        "file": "aerial.yaml",
        "path": "User/RobotConfig/aerial.yaml",
        "summary": "姿态、遥控、云台、步兵发射机构、主机通信"
      }
    ],
    "functions": [
      "姿态",
      "遥控",
      "云台",
      "步兵发射机构",
      "主机通信"
    ],
    "modules": [
      "BMI088",
      "MadgwickAHRS",
      "DR16",
      "Gimbal",
      "InfantryLauncher",
      "SharedTopic",
      "SharedTopicClient"
    ],
    "command": "xrobot_gen_main --config User/RobotConfig/aerial.yaml",
    "docs": [
      {
        "href": "/电控组/robot-configs",
        "label": "机器人配置"
      },
      {
        "href": "/电控组/hardware-mapping",
        "label": "外设映射"
      }
    ]
  },
  {
    "id": "dart",
    "name": "飞镖",
    "glyph": "镖",
    "refereeId": "8",
    "files": [
      {
        "file": "dart.yaml",
        "path": "User/RobotConfig/dart.yaml",
        "summary": "电机、遥控、裁判、Dart、主机通信"
      }
    ],
    "functions": [
      "电机",
      "遥控",
      "裁判",
      "Dart",
      "主机通信"
    ],
    "modules": [
      "RMMotor",
      "DR16",
      "Referee",
      "Dart",
      "SharedTopic",
      "SharedTopicClient"
    ],
    "command": "xrobot_gen_main --config User/RobotConfig/dart.yaml",
    "docs": [
      {
        "href": "/电控组/robot-configs",
        "label": "机器人配置"
      },
      {
        "href": "/电控组/modules",
        "label": "模块索引"
      }
    ]
  }
];

/** Files in the table that the home page does not show (no complete robot yet). */
export const OMITTED_CONFIGS: { file: string; summary: string }[] = [
  {
    "file": "helm_infantry.yaml",
    "summary": "仅 BlinkLED"
  },
  {
    "file": "radar.yaml",
    "summary": "仅 BlinkLED"
  },
  {
    "file": "wheel_leg.yaml",
    "summary": "仅 BlinkLED"
  }
];
